### ISSUE TITLE
Linear Combination transform

### ISSUE THREAD

**Issue by glennmoy** [invenia/Transforms.jl#5]
A transform that computes a linear combination of columns in an array.

MWE
```julia
x = rand(3, 2)

lc = LinearCombination([0.1, 0.9])

Transform.apply(x, lc; cols=[1, 2])
```

A few things:

First.
This is probably just a repackaging of [`Statistics.mean`](https://juliastats.org/StatsBase.jl/stable/means/#Statistics.mean) which is just a weighted sum.
Instead of calling this inside `LinearCombination` might it be better/more flexible to make a Transform that accepts generic functions as transformations? 

Second.
Since this is a many-to-one transform, doesn't seem possible that a mutating form is possible.

**Comment by nicoleepp** [comment]
A mutating function would only be possible for some of the data types, mainly dataframes or namedtuples we could just append a new column with the linear combination. But it would be confusing just to allow it for some types when that doesn't make sense for arrays. If the users want this third col they could easily just assign the result of the transform to said new column (and this would probably be better anyway since they can then name it appropriately)

**Comment by glennmoy** [comment]
> A mutating function would only be possible for some of the data types, mainly dataframes or namedtuples we could just append a new column with the linear combination. But it would be confusing just to allow it for some types when that doesn't make sense for arrays. If the users want this third col they could easily just assign the result of the transform to said new column (and this would probably be better anyway since they can then name it appropriately)

yeah this seems sensible.

I think we should define what we mean by "mutating" in the docs more clearly (for ourselves and others), which is any operation that mutates the elements of the columns passed in and not necessarily adding more columns to the container.

**Comment by bencottier** [comment]
I note we're restricting this to apply to columns. So if a user wants to apply to rows or some dimension beyond 2, they will have to reshape? Maybe that's fair, but just wondering if you considered this @glennmoy .

**Comment by nicoleepp** [comment]
I think we are restricting to cols because that's what makes sense with what we do internally but I may be wrong. If we wanted to apply to rows as well we could:
1. change the weights to be a matrix corresponding to a weight per element
2. have a separate Transform for each
3. Have a kwarg that identifies if the user wants it applied to rows or cols

**Comment by bencottier** [comment]
I also assumed we currently use cols. Option (3) makes the most sense to me. I don't think we've decided this yet, but one idea on the table (if I understood correctly) is arrays with more than 2 axes, to avoid long-winded column names in a 2D table (with the downside being headaches). So that's where supporting other axes would be most worthwhile.

**Comment by glennmoy** [comment]
I've commented on the PR but yeah, option 3 is sensible.
